/* Shared UI translations for HerdCare prototype pages. */
(() => {
  const words = {
    hi: {
      "ACTIVE FARM":"सक्रिय फार्म","Overview":"डैशबोर्ड","My cattle":"मेरे पशु","Health history":"स्वास्थ्य इतिहास","Sensor readings":"सेंसर रीडिंग","Diet & medication":"आहार और दवा","Find a vet":"पशु चिकित्सक खोजें","GPS tracker":"GPS ट्रैकर","Animal library":"पशु लाइब्रेरी","Vet Portal":"डॉक्टर पोर्टल","Livestock":"पशुधन",
      "Connected sensor":"कनेक्टेड सेंसर","Sensor paused":"सेंसर रुका हुआ","Manual entry mode":"मैन्युअल एंट्री मोड","Cattle health record":"पशु स्वास्थ्य रिकॉर्ड","Good morning, Rohan":"सुप्रभात, रोहन","Add health note":"स्वास्थ्य नोट जोड़ें","New photo check":"नई फोटो जाँच","Temperature needs attention.":"तापमान पर ध्यान देने की ज़रूरत है।","Body temperature":"शरीर का तापमान","Sensor details":"सेंसर विवरण","Photo health check":"फोटो स्वास्थ्य जाँच","Upload photo":"फोटो अपलोड करें","No photo uploaded":"कोई फोटो अपलोड नहीं है","Recent health record":"हाल का स्वास्थ्य रिकॉर्ड","View all history":"पूरा इतिहास देखें","Care actions":"देखभाल के कार्य","Contact vet":"डॉक्टर से संपर्क करें","Today’s diet":"आज का आहार","Edit plan":"योजना बदलें","Medication & reminders":"दवा और रिमाइंडर","Manage":"प्रबंधित करें","Nearby veterinarians":"नज़दीकी पशु चिकित्सक","View all":"सभी देखें","Directions":"रास्ता देखें","Open directions":"रास्ता खोलें","Call":"कॉल करें",
      "Monitoring closely":"करीबी निगरानी में","Looks stable":"स्थिति स्थिर है","Urgent veterinary attention":"तुरंत पशु-चिकित्सा सहायता","Estimated wellness":"अनुमानित स्वास्थ्य","Based on logged signals and records.":"दर्ज संकेतों और रिकॉर्ड पर आधारित।","Breed":"नस्ल","Age":"उम्र","Weight":"वजन","Last calved":"अंतिम बछड़ा","Check appetite and eye area":"भूख और आँखों के क्षेत्र की जाँच करें","Continue routine monitoring":"नियमित निगरानी जारी रखें","Photo is stored in this animal’s record":"फोटो इस पशु के रिकॉर्ड में सहेजा गया है","AI integration point ready for a vision service":"विज़न सेवा के लिए AI इंटीग्रेशन तैयार है","Add observation →":"अवलोकन जोड़ें →","Morning feed":"सुबह का चारा","Concentrate":"कंसन्ट्रेट","Water target":"पानी का लक्ष्य","Supplement":"सप्लीमेंट","Green fodder":"हरा चारा","Fresh water":"ताज़ा पानी","Mineral mix":"मिनरल मिक्स","Today":"आज",
      "Health history":"स्वास्थ्य इतिहास","What to log":"क्या दर्ज करें","Temperature sensor":"तापमान सेंसर","Update reading":"रीडिंग अपडेट करें","Current body temperature (°C)":"वर्तमान शरीर तापमान (°C)","Save temperature":"तापमान सहेजें","Sensor connection":"सेंसर कनेक्शन","Connected and syncing":"कनेक्टेड और सिंक हो रहा है","Paused — manual entry mode":"रुका हुआ — मैन्युअल एंट्री मोड","Diet plan":"आहार योजना","Add diet item":"आहार आइटम जोड़ें","Add":"जोड़ें","Remove":"हटाएँ","Medication":"दवा","Find veterinary help":"पशु चिकित्सा सहायता खोजें","Add a local vet":"स्थानीय डॉक्टर जोड़ें","Open now":"अभी खुला है","24-hour service":"24 घंटे सेवा","Open until 20:00":"20:00 तक खुला",
      "Live location & safety":"लाइव लोकेशन और सुरक्षा","Track cattle inside the designated Green Valley Farm boundary.":"निर्धारित ग्रीन वैली फार्म सीमा के भीतर पशुओं को ट्रैक करें।","TRACKER CONNECTED":"ट्रैकर कनेक्टेड","TRACKER OFFLINE":"ट्रैकर ऑफलाइन","current route":"वर्तमान मार्ग","Updated":"अपडेट किया गया","Geofence status":"सीमा स्थिति","ALERT":"अलर्ट","SAFE":"सुरक्षित","Tracked animal":"ट्रैक किया गया पशु","Farm boundary radius:":"फार्म सीमा त्रिज्या:","Movement insight":"गतिविधि जानकारी","Simulate boundary exit":"सीमा से बाहर जाना दिखाएँ","Return to farm":"फार्म लौटाएँ","Farm boundary":"फार्म सीमा","Current location":"वर्तमान स्थान","Outside boundary":"सीमा के बाहर","Recent travel direction":"हाल की यात्रा दिशा",
      "Open animal knowledge":"खुला पशु ज्ञान","Animal & breed library":"पशु और नस्ल लाइब्रेरी","Breed profiles for everyday reference":"रोज़मर्रा के संदर्भ के लिए नस्ल प्रोफ़ाइल","Search open knowledge":"खुला ज्ञान खोजें","All":"सभी","Cattle":"गाय-भैंस","Dog":"कुत्ता","Cat":"बिल्ली","Sheep":"भेड़","Bird":"पक्षी","Goat":"बकरी","Typical lifespan":"सामान्य आयु","Suitable focus":"उपयुक्त उद्देश्य","Diet focus:":"आहार केंद्र:","Open knowledge source ↗":"खुला ज्ञान स्रोत ↗","Ask Aashu →":"आशु से पूछें →","Open knowledge result":"खुला ज्ञान परिणाम",
      "Professional directory":"पेशेवर निर्देशिका","Register a professional profile so local animal owners can find and contact you.":"पेशेवर प्रोफ़ाइल बनाएँ ताकि स्थानीय पशु-पालक आपको खोज और संपर्क कर सकें।","Create your vet profile":"अपनी डॉक्टर प्रोफ़ाइल बनाएँ","Share professional details, practice location, and availability.":"पेशेवर विवरण, क्लिनिक स्थान और उपलब्धता साझा करें।","Full name":"पूरा नाम","Clinic or practice":"क्लिनिक या प्रैक्टिस","Veterinary registration number":"पशु चिकित्सा पंजीकरण नंबर","Specialty":"विशेषज्ञता","Phone number":"फोन नंबर","Practice address":"क्लिनिक पता","Availability":"उपलब्धता","Create vet profile":"डॉक्टर प्रोफ़ाइल बनाएँ","Veterinarian directory":"पशु चिकित्सक निर्देशिका","profiles":"प्रोफ़ाइल","Profile pending verification":"प्रोफ़ाइल सत्यापन लंबित है","Verified directory listing":"सत्यापित निर्देशिका सूची",
      "Animal-care assistant":"पशु-देखभाल सहायक","Send":"भेजें","Fever and behaviour":"बुखार और व्यवहार","Feed and water":"चारा और पानी","Vaccines":"टीके","Ask about health, diet, vaccines…":"स्वास्थ्य, आहार, टीकों के बारे में पूछें…",
      "Farm value & circular resources":"कृषि मूल्य और चक्रीय संसाधन","Livestock products":"पशुधन उत्पाद","Back to HerdCare":"हर्डकेयर पर वापस","From animal care to useful products":"पशु देखभाल से उपयोगी उत्पाद तक","Food":"खाद्य","Materials":"सामग्री","Farm input":"कृषि इनपुट","Energy":"ऊर्जा","View guide →":"गाइड देखें →","How it is made":"यह कैसे बनता है","Why it matters":"यह क्यों महत्वपूर्ण है","Important consideration":"महत्वपूर्ण विचार","Ask Aashu about this product":"इस उत्पाद के बारे में आशु से पूछें","Back to product library":"उत्पाद लाइब्रेरी पर वापस",
      "Search an animal or breed — e.g. Sahiwal, dog, Golden Retriever":"पशु या नस्ल खोजें — जैसे साहीवाल, कुत्ता, गोल्डन रिट्रीवर","Search name, clinic, specialty, or area":"नाम, क्लिनिक, विशेषज्ञता या क्षेत्र खोजें","Ask Aashu":"आशु से पूछें","Website language":"वेबसाइट भाषा","Website language":"वेबसाइट भाषा"
    },
    bn: {
      "ACTIVE FARM":"সক্রিয় খামার","Overview":"ড্যাশবোর্ড","My cattle":"আমার গবাদি পশু","Health history":"স্বাস্থ্য ইতিহাস","Sensor readings":"সেন্সর রিডিং","Diet & medication":"খাদ্য ও ওষুধ","Find a vet":"পশু চিকিৎসক খুঁজুন","GPS tracker":"GPS ট্র্যাকার","Animal library":"প্রাণী লাইব্রেরি","Vet Portal":"ভেট পোর্টাল","Livestock":"পশুপালন",
      "Connected sensor":"সংযুক্ত সেন্সর","Sensor paused":"সেন্সর বন্ধ","Manual entry mode":"ম্যানুয়াল এন্ট্রি মোড","Cattle health record":"গবাদি পশুর স্বাস্থ্য রেকর্ড","Good morning, Rohan":"সুপ্রভাত, রোহন","Add health note":"স্বাস্থ্য নোট যোগ করুন","New photo check":"নতুন ছবি পরীক্ষা","Temperature needs attention.":"তাপমাত্রায় মনোযোগ দরকার।","Body temperature":"শরীরের তাপমাত্রা","Sensor details":"সেন্সর বিবরণ","Photo health check":"ছবির স্বাস্থ্য পরীক্ষা","Upload photo":"ছবি আপলোড করুন","No photo uploaded":"কোনো ছবি আপলোড করা হয়নি","Recent health record":"সাম্প্রতিক স্বাস্থ্য রেকর্ড","View all history":"সব ইতিহাস দেখুন","Care actions":"যত্নের কাজ","Contact vet":"চিকিৎসকের সঙ্গে যোগাযোগ করুন","Today’s diet":"আজকের খাদ্য","Edit plan":"পরিকল্পনা সম্পাদনা করুন","Medication & reminders":"ওষুধ ও অনুস্মারক","Manage":"পরিচালনা করুন","Nearby veterinarians":"নিকটবর্তী পশু চিকিৎসক","View all":"সব দেখুন","Directions":"দিকনির্দেশ","Open directions":"দিকনির্দেশ খুলুন","Call":"কল করুন",
      "Monitoring closely":"নিবিড় পর্যবেক্ষণে","Looks stable":"স্থিতিশীল দেখাচ্ছে","Urgent veterinary attention":"জরুরি পশু চিকিৎসা প্রয়োজন","Estimated wellness":"আনুমানিক সুস্থতা","Based on logged signals and records.":"সংরক্ষিত সংকেত ও রেকর্ডের ভিত্তিতে।","Breed":"জাত","Age":"বয়স","Weight":"ওজন","Last calved":"সর্বশেষ বাচ্চা দিয়েছে","Check appetite and eye area":"ক্ষুধা ও চোখের অংশ পরীক্ষা করুন","Continue routine monitoring":"নিয়মিত পর্যবেক্ষণ চালিয়ে যান","Photo is stored in this animal’s record":"ছবি এই প্রাণীর রেকর্ডে রাখা হয়েছে","AI integration point ready for a vision service":"ভিশন পরিষেবার জন্য AI ইন্টিগ্রেশন প্রস্তুত","Add observation →":"পর্যবেক্ষণ যোগ করুন →","Morning feed":"সকালের খাদ্য","Concentrate":"কনসেনট্রেট","Water target":"পানির লক্ষ্য","Supplement":"পরিপূরক","Green fodder":"সবুজ খাদ্য","Fresh water":"পরিষ্কার পানি","Mineral mix":"মিনারেল মিশ্রণ","Today":"আজ",
      "Health history":"স্বাস্থ্য ইতিহাস","What to log":"কী সংরক্ষণ করবেন","Temperature sensor":"তাপমাত্রা সেন্সর","Update reading":"রিডিং আপডেট করুন","Current body temperature (°C)":"বর্তমান শরীরের তাপমাত্রা (°C)","Save temperature":"তাপমাত্রা সংরক্ষণ করুন","Sensor connection":"সেন্সর সংযোগ","Connected and syncing":"সংযুক্ত এবং সিঙ্ক হচ্ছে","Paused — manual entry mode":"বন্ধ — ম্যানুয়াল এন্ট্রি মোড","Diet plan":"খাদ্য পরিকল্পনা","Add diet item":"খাদ্য আইটেম যোগ করুন","Add":"যোগ করুন","Remove":"সরান","Medication":"ওষুধ","Find veterinary help":"পশু চিকিৎসা সহায়তা খুঁজুন","Add a local vet":"স্থানীয় চিকিৎসক যোগ করুন","Open now":"এখন খোলা","24-hour service":"২৪ ঘণ্টা সেবা","Open until 20:00":"20:00 পর্যন্ত খোলা",
      "Live location & safety":"লাইভ অবস্থান ও নিরাপত্তা","Track cattle inside the designated Green Valley Farm boundary.":"নির্ধারিত গ্রিন ভ্যালি ফার্ম সীমার মধ্যে গবাদি পশু ট্র্যাক করুন।","TRACKER CONNECTED":"ট্র্যাকার সংযুক্ত","TRACKER OFFLINE":"ট্র্যাকার অফলাইন","current route":"বর্তমান রুট","Updated":"আপডেট হয়েছে","Geofence status":"জিওফেন্স অবস্থা","ALERT":"সতর্কতা","SAFE":"নিরাপদ","Tracked animal":"ট্র্যাক করা প্রাণী","Farm boundary radius:":"খামারের সীমানা ব্যাসার্ধ:","Movement insight":"চলাচলের তথ্য","Simulate boundary exit":"সীমানা ছাড়ার নমুনা দেখান","Return to farm":"খামারে ফেরত আনুন","Farm boundary":"খামারের সীমানা","Current location":"বর্তমান অবস্থান","Outside boundary":"সীমানার বাইরে","Recent travel direction":"সাম্প্রতিক ভ্রমণের দিক",
      "Open animal knowledge":"খোলা প্রাণী জ্ঞান","Animal & breed library":"প্রাণী ও জাতের লাইব্রেরি","Breed profiles for everyday reference":"প্রতিদিনের ব্যবহারের জন্য জাতের প্রোফাইল","Search open knowledge":"খোলা জ্ঞান খুঁজুন","All":"সব","Cattle":"গবাদি পশু","Dog":"কুকুর","Cat":"বিড়াল","Sheep":"ভেড়া","Bird":"পাখি","Goat":"ছাগল","Typical lifespan":"সাধারণ আয়ু","Suitable focus":"উপযুক্ত লক্ষ্য","Diet focus:":"খাদ্যের বিষয়:","Open knowledge source ↗":"খোলা জ্ঞান উৎস ↗","Ask Aashu →":"আশুকে জিজ্ঞাসা করুন →","Open knowledge result":"খোলা জ্ঞান ফলাফল",
      "Professional directory":"পেশাদার নির্দেশিকা","Register a professional profile so local animal owners can find and contact you.":"পেশাদার প্রোফাইল তৈরি করুন যাতে স্থানীয় পশু মালিকরা আপনাকে খুঁজে ও যোগাযোগ করতে পারেন।","Create your vet profile":"আপনার ভেট প্রোফাইল তৈরি করুন","Share professional details, practice location, and availability.":"পেশাদার তথ্য, প্র্যাকটিসের স্থান এবং উপলব্ধতা শেয়ার করুন।","Full name":"পুরো নাম","Clinic or practice":"ক্লিনিক বা প্র্যাকটিস","Veterinary registration number":"পশু চিকিৎসা নিবন্ধন নম্বর","Specialty":"বিশেষত্ব","Phone number":"ফোন নম্বর","Practice address":"প্র্যাকটিসের ঠিকানা","Availability":"উপলব্ধতা","Create vet profile":"ভেট প্রোফাইল তৈরি করুন","Veterinarian directory":"পশু চিকিৎসক নির্দেশিকা","profiles":"প্রোফাইল","Profile pending verification":"প্রোফাইল যাচাই বাকি","Verified directory listing":"যাচাইকৃত নির্দেশিকা তালিকা",
      "Animal-care assistant":"প্রাণী পরিচর্যা সহকারী","Send":"পাঠান","Fever and behaviour":"জ্বর ও আচরণ","Feed and water":"খাদ্য ও পানি","Vaccines":"টিকা","Ask about health, diet, vaccines…":"স্বাস্থ্য, খাদ্য, টিকা সম্পর্কে জিজ্ঞাসা করুন…",
      "Farm value & circular resources":"খামারের মূল্য ও চক্রাকার সম্পদ","Livestock products":"পশুপালন পণ্য","Back to HerdCare":"হার্ডকেয়ারে ফিরে যান","From animal care to useful products":"প্রাণী পরিচর্যা থেকে ব্যবহারযোগ্য পণ্য","Food":"খাদ্য","Materials":"উপকরণ","Farm input":"কৃষি উপকরণ","Energy":"শক্তি","View guide →":"গাইড দেখুন →","How it is made":"কীভাবে তৈরি হয়","Why it matters":"কেন গুরুত্বপূর্ণ","Important consideration":"গুরুত্বপূর্ণ বিবেচনা","Ask Aashu about this product":"এই পণ্য সম্পর্কে আশুকে জিজ্ঞাসা করুন","Back to product library":"পণ্য তালিকায় ফিরে যান",
      "Search an animal or breed — e.g. Sahiwal, dog, Golden Retriever":"প্রাণী বা জাত খুঁজুন — যেমন সাহিওয়াল, কুকুর, গোল্ডেন রিট্রিভার","Search name, clinic, specialty, or area":"নাম, ক্লিনিক, বিশেষত্ব বা এলাকা খুঁজুন","Ask Aashu":"আশুকে জিজ্ঞাসা করুন","Website language":"ওয়েবসাইটের ভাষা"
    },
    mr: {
      "ACTIVE FARM":"सक्रिय शेत","Overview":"आढावा","My cattle":"माझी जनावरे","Health history":"आरोग्य इतिहास","Sensor readings":"सेन्सर रीडिंग","Diet & medication":"आहार आणि औषधे","Find a vet":"पशुवैद्य शोधा","GPS tracker":"GPS ट्रॅकर","Animal library":"प्राणी लायब्ररी","Vet Portal":"पशुवैद्य पोर्टल","Livestock":"पशुधन",
      "Connected sensor":"जोडलेला सेन्सर","Sensor paused":"सेन्सर थांबवलेला","Manual entry mode":"हस्तचालित नोंद मोड","Cattle health record":"जनावरांचा आरोग्य रेकॉर्ड","Good morning, Rohan":"सुप्रभात, रोहन","Add health note":"आरोग्य नोंद जोडा","New photo check":"नवीन फोटो तपासणी","Temperature needs attention.":"तापमानाकडे लक्ष देणे आवश्यक आहे।","Body temperature":"शरीराचे तापमान","Sensor details":"सेन्सर तपशील","Photo health check":"फोटो आरोग्य तपासणी","Upload photo":"फोटो अपलोड करा","No photo uploaded":"फोटो अपलोड केलेला नाही","Recent health record":"अलीकडील आरोग्य रेकॉर्ड","View all history":"संपूर्ण इतिहास पहा","Care actions":"काळजीची कामे","Contact vet":"डॉक्टरांशी संपर्क करा","Today’s diet":"आजचा आहार","Edit plan":"योजना बदला","Medication & reminders":"औषधे आणि स्मरणपत्रे","Manage":"व्यवस्थापित करा","Nearby veterinarians":"जवळचे पशुवैद्य","View all":"सर्व पहा","Directions":"मार्गदर्शन","Open directions":"मार्ग उघडा","Call":"कॉल करा",
      "Monitoring closely":"काळजीपूर्वक निरीक्षणात","Looks stable":"स्थिती स्थिर दिसते","Urgent veterinary attention":"तातडीची पशुवैद्यकीय मदत","Estimated wellness":"अंदाजे आरोग्य","Based on logged signals and records.":"नोंदवलेल्या संकेत आणि रेकॉर्डवर आधारित।","Breed":"जात","Age":"वय","Weight":"वजन","Last calved":"शेवटचा विणण्याचा दिवस","Check appetite and eye area":"भूक आणि डोळ्यांचा भाग तपासा","Continue routine monitoring":"नियमित निरीक्षण सुरू ठेवा","Photo is stored in this animal’s record":"फोटो या जनावराच्या नोंदीत जतन केला आहे","AI integration point ready for a vision service":"व्हिजन सेवेसाठी AI जोडणी तयार आहे","Add observation →":"निरीक्षण जोडा →","Morning feed":"सकाळचा चारा","Concentrate":"कन्सन्ट्रेट","Water target":"पाण्याचे लक्ष्य","Supplement":"पूरक","Green fodder":"हिरवा चारा","Fresh water":"ताजे पाणी","Mineral mix":"खनिज मिश्रण","Today":"आज",
      "Health history":"आरोग्य इतिहास","What to log":"काय नोंदवायचे","Temperature sensor":"तापमान सेन्सर","Update reading":"रीडिंग अद्यतनित करा","Current body temperature (°C)":"सध्याचे शरीर तापमान (°C)","Save temperature":"तापमान जतन करा","Sensor connection":"सेन्सर कनेक्शन","Connected and syncing":"जोडलेले आणि सिंक होत आहे","Paused — manual entry mode":"थांबवलेले — हस्तचालित नोंद मोड","Diet plan":"आहार योजना","Add diet item":"आहार घटक जोडा","Add":"जोडा","Remove":"काढा","Medication":"औषध","Find veterinary help":"पशुवैद्यकीय मदत शोधा","Add a local vet":"स्थानिक डॉक्टर जोडा","Open now":"आता खुले","24-hour service":"24 तास सेवा","Open until 20:00":"20:00 पर्यंत खुले",
      "Live location & safety":"थेट स्थान आणि सुरक्षितता","Track cattle inside the designated Green Valley Farm boundary.":"नियोजित ग्रीन व्हॅली फार्म हद्दीत जनावरांचा मागोवा घ्या।","TRACKER CONNECTED":"ट्रॅकर जोडलेला","TRACKER OFFLINE":"ट्रॅकर ऑफलाइन","current route":"सध्याचा मार्ग","Updated":"अद्यतनित","Geofence status":"जिओफेन्स स्थिती","ALERT":"इशारा","SAFE":"सुरक्षित","Tracked animal":"ट्रॅक केलेले जनावर","Farm boundary radius:":"शेत हद्द त्रिज्या:","Movement insight":"हालचालीची माहिती","Simulate boundary exit":"सीमाबाहेर जाणे दाखवा","Return to farm":"शेतात परत आणा","Farm boundary":"शेताची हद्द","Current location":"सध्याचे स्थान","Outside boundary":"हद्दीबाहेर","Recent travel direction":"अलीकडील प्रवासाची दिशा",
      "Open animal knowledge":"खुले प्राणी ज्ञान","Animal & breed library":"प्राणी आणि जातींची लायब्ररी","Breed profiles for everyday reference":"दररोजच्या संदर्भासाठी जातीची प्रोफाइल","Search open knowledge":"खुले ज्ञान शोधा","All":"सर्व","Cattle":"गुरे","Dog":"कुत्रा","Cat":"मांजर","Sheep":"मेंढी","Bird":"पक्षी","Goat":"शेळी","Typical lifespan":"सामान्य आयुर्मान","Suitable focus":"योग्य उद्देश","Diet focus:":"आहाराचा भर:","Open knowledge source ↗":"खुला ज्ञान स्रोत ↗","Ask Aashu →":"आशूला विचारा →","Open knowledge result":"खुला ज्ञान परिणाम",
      "Professional directory":"व्यावसायिक निर्देशिका","Register a professional profile so local animal owners can find and contact you.":"व्यावसायिक प्रोफाइल तयार करा जेणेकरून स्थानिक पशुपालक तुम्हाला शोधू आणि संपर्क करू शकतील।","Create your vet profile":"तुमची पशुवैद्य प्रोफाइल तयार करा","Share professional details, practice location, and availability.":"व्यावसायिक तपशील, प्रॅक्टिसचे स्थान आणि उपलब्धता शेअर करा।","Full name":"पूर्ण नाव","Clinic or practice":"क्लिनिक किंवा प्रॅक्टिस","Veterinary registration number":"पशुवैद्यकीय नोंदणी क्रमांक","Specialty":"विशेषता","Phone number":"फोन नंबर","Practice address":"प्रॅक्टिसचा पत्ता","Availability":"उपलब्धता","Create vet profile":"पशुवैद्य प्रोफाइल तयार करा","Veterinarian directory":"पशुवैद्य निर्देशिका","profiles":"प्रोफाइल","Profile pending verification":"प्रोफाइल पडताळणी प्रलंबित","Verified directory listing":"पडताळलेली निर्देशिका सूची",
      "Animal-care assistant":"पशु-देखभाल सहाय्यक","Send":"पाठवा","Fever and behaviour":"ताप आणि वर्तन","Feed and water":"चारा आणि पाणी","Vaccines":"लसी","Ask about health, diet, vaccines…":"आरोग्य, आहार, लसींबद्दल विचारा…",
      "Farm value & circular resources":"शेती मूल्य आणि चक्रीय संसाधने","Livestock products":"पशुधन उत्पादने","Back to HerdCare":"हर्डकेअरवर परत जा","From animal care to useful products":"प्राणी काळजीपासून उपयुक्त उत्पादनांपर्यंत","Food":"अन्न","Materials":"साहित्य","Farm input":"शेती इनपुट","Energy":"ऊर्जा","View guide →":"मार्गदर्शक पहा →","How it is made":"कसे बनवले जाते","Why it matters":"हे का महत्त्वाचे आहे","Important consideration":"महत्त्वाचा विचार","Ask Aashu about this product":"या उत्पादनाबद्दल आशूला विचारा","Back to product library":"उत्पादन लायब्ररीकडे परत जा",
      "Search an animal or breed — e.g. Sahiwal, dog, Golden Retriever":"प्राणी किंवा जात शोधा — उदा. साहीवाल, कुत्रा, गोल्डन रिट्रीव्हर","Search name, clinic, specialty, or area":"नाव, क्लिनिक, विशेषता किंवा क्षेत्र शोधा","Ask Aashu":"आशूला विचारा","Website language":"वेबसाइट भाषा"
    }
  };
  Object.assign(words.hi, {
    "Here’s Bella’s current health picture.":"यहाँ बेला के वर्तमान स्वास्थ्य की जानकारी है।",
    "Check appetite and eye area":"भूख और आँखों के क्षेत्र की जाँच करें",
    "Record any reduced eating, discharge, swelling, or unusual behaviour.":"खाने में कमी, स्राव, सूजन या असामान्य व्यवहार दर्ज करें।",
    "Bella’s readings are currently close to her usual range.":"बेला की रीडिंग अभी उसके सामान्य दायरे के करीब हैं।",
    "Continue routine monitoring":"नियमित निगरानी जारी रखें",
    "Photo is stored in this animal’s record":"फोटो इस पशु के रिकॉर्ड में सहेजा गया है",
    "Demo observation: verify eye area in person":"डेमो अवलोकन: आँखों के क्षेत्र को स्वयं जाँचें",
    "HerdCare supports monitoring and recordkeeping. It does not diagnose disease; use a qualified veterinarian for medical decisions.":"हर्डकेयर निगरानी और रिकॉर्ड रखने में मदद करता है। यह बीमारी का निदान नहीं करता; चिकित्सा निर्णयों के लिए योग्य पशु चिकित्सक से संपर्क करें।",
    "Every entry for Bella is saved on this device.":"बेला की हर प्रविष्टि इस डिवाइस में सहेजी गई है।",
    "Use this record for temperature changes, appetite, water intake, behaviour, visible symptoms, treatments and veterinary visits.":"इस रिकॉर्ड में तापमान, भूख, पानी, व्यवहार, दिखाई देने वाले लक्षण, उपचार और डॉक्टर की यात्राएँ दर्ज करें।",
    "Well-kept records help a veterinarian understand the animal’s history quickly.":"अच्छे रिकॉर्ड पशु चिकित्सक को पशु का इतिहास जल्दी समझने में मदद करते हैं।",
    "Manage Bella’s temperature monitoring and add an immediate reading.":"बेला की तापमान निगरानी प्रबंधित करें और तुरंत रीडिंग जोड़ें।",
    "A real installation will send readings from a temperature sensor through a secure device gateway.":"वास्तविक इंस्टॉलेशन सुरक्षित डिवाइस गेटवे से तापमान सेंसर की रीडिंग भेजेगा।",
    "Manage Bella’s daily feed plan and treatment reminders.":"बेला की दैनिक आहार योजना और उपचार रिमाइंडर प्रबंधित करें।",
    "Use the call button to contact a vet. The directions button opens the listed clinic location in Maps.":"डॉक्टर से संपर्क करने के लिए कॉल बटन का उपयोग करें। रास्ता बटन मैप में क्लिनिक खोलता है।",
    "In a production system, clinic listings should be verified and kept up to date with vet consent.":"वास्तविक सिस्टम में डॉक्टर की सहमति से क्लिनिक सूची सत्यापित और अद्यतन रखनी चाहिए।",
    "Tag ID:":"टैग आईडी:","Updated ":"अद्यतन ","GPS alert:":"GPS चेतावनी:","GPS update:":"GPS अपडेट:"
  });
  Object.assign(words.bn, {
    "Here’s Bella’s current health picture.":"এখানে বেলার বর্তমান স্বাস্থ্যের চিত্র রয়েছে।",
    "Record any reduced eating, discharge, swelling, or unusual behaviour.":"খাওয়া কমে যাওয়া, স্রাব, ফোলা বা অস্বাভাবিক আচরণ নথিবদ্ধ করুন।",
    "Bella’s readings are currently close to her usual range.":"বেলার রিডিং এখন তার স্বাভাবিক সীমার কাছাকাছি।",
    "Demo observation: verify eye area in person":"ডেমো পর্যবেক্ষণ: চোখের অংশ সরাসরি পরীক্ষা করুন",
    "HerdCare supports monitoring and recordkeeping. It does not diagnose disease; use a qualified veterinarian for medical decisions.":"হার্ডকেয়ার পর্যবেক্ষণ ও রেকর্ড রাখতে সহায়তা করে। এটি রোগ নির্ণয় করে না; চিকিৎসা সিদ্ধান্তের জন্য যোগ্য পশু চিকিৎসকের পরামর্শ নিন।",
    "Every entry for Bella is saved on this device.":"বেলার প্রতিটি এন্ট্রি এই ডিভাইসে সংরক্ষিত আছে।",
    "Use this record for temperature changes, appetite, water intake, behaviour, visible symptoms, treatments and veterinary visits.":"তাপমাত্রার পরিবর্তন, ক্ষুধা, পানির গ্রহণ, আচরণ, দৃশ্যমান লক্ষণ, চিকিৎসা এবং চিকিৎসক পরিদর্শনের জন্য এই রেকর্ড ব্যবহার করুন।",
    "Well-kept records help a veterinarian understand the animal’s history quickly.":"ভালো রেকর্ড পশু চিকিৎসককে প্রাণীর ইতিহাস দ্রুত বুঝতে সাহায্য করে।",
    "Manage Bella’s temperature monitoring and add an immediate reading.":"বেলার তাপমাত্রা পর্যবেক্ষণ পরিচালনা করুন এবং তাৎক্ষণিক রিডিং যোগ করুন।",
    "A real installation will send readings from a temperature sensor through a secure device gateway.":"বাস্তব স্থাপনা একটি নিরাপদ ডিভাইস গেটওয়ের মাধ্যমে তাপমাত্রা সেন্সরের রিডিং পাঠাবে।",
    "Manage Bella’s daily feed plan and treatment reminders.":"বেলার দৈনিক খাদ্য পরিকল্পনা ও চিকিৎসার অনুস্মারক পরিচালনা করুন।",
    "Use the call button to contact a vet. The directions button opens the listed clinic location in Maps.":"চিকিৎসকের সাথে যোগাযোগ করতে কল বোতাম ব্যবহার করুন। দিকনির্দেশ বোতাম ম্যাপে ক্লিনিক খুলবে।",
    "In a production system, clinic listings should be verified and kept up to date with vet consent.":"প্রোডাকশন সিস্টেমে চিকিৎসকের সম্মতিতে ক্লিনিক তালিকা যাচাই ও হালনাগাদ রাখতে হবে।",
    "Tag ID:":"ট্যাগ আইডি:","Updated ":"আপডেট ","GPS alert:":"GPS সতর্কতা:","GPS update:":"GPS আপডেট:"
  });
  Object.assign(words.mr, {
    "Here’s Bella’s current health picture.":"येथे बेलाच्या सध्याच्या आरोग्याची माहिती आहे।",
    "Record any reduced eating, discharge, swelling, or unusual behaviour.":"खाणे कमी होणे, स्त्राव, सूज किंवा असामान्य वर्तनाची नोंद करा।",
    "Bella’s readings are currently close to her usual range.":"बेलाची रीडिंग सध्या तिच्या नेहमीच्या मर्यादेजवळ आहे।",
    "Demo observation: verify eye area in person":"डेमो निरीक्षण: डोळ्यांचा भाग प्रत्यक्ष तपासा",
    "HerdCare supports monitoring and recordkeeping. It does not diagnose disease; use a qualified veterinarian for medical decisions.":"हर्डकेअर निरीक्षण आणि नोंदी ठेवण्यास मदत करते। ते आजाराचे निदान करत नाही; वैद्यकीय निर्णयांसाठी पात्र पशुवैद्याचा सल्ला घ्या।",
    "Every entry for Bella is saved on this device.":"बेलाची प्रत्येक नोंद या उपकरणावर जतन केली आहे।",
    "Use this record for temperature changes, appetite, water intake, behaviour, visible symptoms, treatments and veterinary visits.":"तापमानातील बदल, भूक, पाणी पिणे, वर्तन, दिसणारी लक्षणे, उपचार आणि पशुवैद्य भेटींसाठी ही नोंद वापरा।",
    "Well-kept records help a veterinarian understand the animal’s history quickly.":"चांगल्या नोंदी पशुवैद्याला जनावराचा इतिहास पटकन समजण्यास मदत करतात।",
    "Manage Bella’s temperature monitoring and add an immediate reading.":"बेलाचे तापमान निरीक्षण व्यवस्थापित करा आणि त्वरित रीडिंग जोडा।",
    "A real installation will send readings from a temperature sensor through a secure device gateway.":"वास्तविक प्रणाली सुरक्षित डिव्हाइस गेटवेद्वारे तापमान सेन्सरची रीडिंग पाठवेल।",
    "Manage Bella’s daily feed plan and treatment reminders.":"बेलाची दैनंदिन आहार योजना आणि उपचार स्मरणपत्रे व्यवस्थापित करा।",
    "Use the call button to contact a vet. The directions button opens the listed clinic location in Maps.":"पशुवैद्याशी संपर्क करण्यासाठी कॉल बटण वापरा। मार्ग बटण नकाशात क्लिनिक उघडते।",
    "In a production system, clinic listings should be verified and kept up to date with vet consent.":"वास्तविक प्रणालीमध्ये पशुवैद्याच्या संमतीने क्लिनिक सूची पडताळून अद्ययावत ठेवावी।",
    "Tag ID:":"टॅग आयडी:","Updated ":"अद्यतन ","GPS alert:":"GPS इशारा:","GPS update:":"GPS अद्यतन:"
  });
  Object.assign(words.hi,{"Buffalo":"भैंस","Honeybee":"मधुमक्खी","Rabbit":"खरगोश","Horse":"घोड़ा","Pig":"सूअर","Delete record":"रिकॉर्ड हटाएँ","Personalize animal photo":"पशु की फोटो बदलें","Add a profile photo for this animal. It is stored only in this browser for the prototype.":"इस पशु की प्रोफ़ाइल फोटो जोड़ें। प्रोटोटाइप के लिए यह केवल इस ब्राउज़र में सहेजी जाती है।"});
  Object.assign(words.bn,{"Buffalo":"মহিষ","Honeybee":"মৌমাছি","Rabbit":"খরগোশ","Horse":"ঘোড়া","Pig":"শূকর","Delete record":"রেকর্ড মুছুন","Personalize animal photo":"প্রাণীর ছবি ব্যক্তিগতকরণ করুন","Add a profile photo for this animal. It is stored only in this browser for the prototype.":"এই প্রাণীর প্রোফাইল ছবি যোগ করুন। প্রোটোটাইপের জন্য এটি শুধু এই ব্রাউজারে সংরক্ষিত থাকে।"});
  Object.assign(words.mr,{"Buffalo":"म्हैस","Honeybee":"मधमाशी","Rabbit":"ससा","Horse":"घोडा","Pig":"डुक्कर","Delete record":"नोंद हटवा","Personalize animal photo":"जनावराचा फोटो वैयक्तिकृत करा","Add a profile photo for this animal. It is stored only in this browser for the prototype.":"या जनावराचा प्रोफाइल फोटो जोडा। प्रोटोटाइपसाठी तो फक्त या ब्राउझरमध्ये जतन केला जातो।"});
  /*
   * The prototype renders several screens and dialogs after the first page load.
   * Keep their UI copy here, alongside the first-screen copy above, so changing
   * language never leaves a mixture of English and the selected language.
   */
  const supplementalWords = {
    hi: {
      "Dairy cow":"दूध देने वाली गाय", "Tag ID:":"टैग आईडी:", "Within usual range":"सामान्य सीमा में", "over usual":"सामान्य से अधिक", "Latest photo · saved locally":"नवीनतम फोटो · स्थानीय रूप से सहेजी गई", "No photo uploaded":"कोई फोटो अपलोड नहीं है", "Contact a veterinarian now":"अभी पशु चिकित्सक से संपर्क करें", "The recorded temperature is at or above the urgent threshold.":"दर्ज तापमान तत्काल सहायता की सीमा पर या उससे अधिक है।", "Monitor closely and seek veterinary advice if it persists.":"करीबी निगरानी रखें और स्थिति बनी रहे तो पशु चिकित्सक की सलाह लें।", "Add cattle":"पशु जोड़ें", "Create a new digital health record.":"नया डिजिटल स्वास्थ्य रिकॉर्ड बनाएँ।", "Wellness":"स्वास्थ्य", "What to log":"क्या दर्ज करें", "LIVE":"लाइव", "PAUSED":"रुका हुआ", "Toggle sensor":"सेंसर बदलें", "Only record medication prescribed or approved by a qualified veterinarian.":"केवल योग्य पशु चिकित्सक द्वारा लिखी या स्वीकृत दवा ही दर्ज करें।", "24 HOUR":"24 घंटे", "Cancel":"रद्द करें", "Save":"सहेजें", "Add health record":"स्वास्थ्य रिकॉर्ड जोड़ें", "Save an observation, symptom or treatment note to this animal’s history.":"इस पशु के इतिहास में अवलोकन, लक्षण या उपचार की टिप्पणी सहेजें।", "Entry type":"प्रविष्टि का प्रकार", "General observation":"सामान्य अवलोकन", "Appetite and activity":"भूख और गतिविधि", "Veterinary visit":"पशु चिकित्सक की यात्रा", "Medication update":"दवा अपडेट", "Details":"विवरण", "Temperature (optional, °C)":"तापमान (वैकल्पिक, °C)", "Add photo health check":"फोटो स्वास्थ्य जाँच जोड़ें", "Choose a clear photo. It is saved only in this browser for this prototype.":"स्पष्ट फोटो चुनें। इस प्रोटोटाइप में यह केवल इसी ब्राउज़र में सहेजी जाती है।", "Photo":"फोटो", "Optional note":"वैकल्पिक टिप्पणी", "Add diet item":"आहार आइटम जोड़ें", "Item name":"आइटम का नाम", "Amount":"मात्रा", "Description":"विवरण", "Add medication reminder":"दवा रिमाइंडर जोड़ें", "Keep dosage and scheduling details in the health record.":"खुराक और समय-सारणी का विवरण स्वास्थ्य रिकॉर्ड में रखें।", "Medicine name":"दवा का नाम", "Dosage / instruction":"खुराक / निर्देश", "Due date or timing":"नियत तारीख या समय", "Add local veterinarian":"स्थानीय पशु चिकित्सक जोड़ें", "Save a verified local contact for this prototype.":"इस प्रोटोटाइप के लिए सत्यापित स्थानीय संपर्क सहेजें।", "Veterinarian name":"पशु चिकित्सक का नाम", "Clinic":"क्लिनिक", "Distance (optional)":"दूरी (वैकल्पिक)", "Hours not recorded":"समय दर्ज नहीं है", "Temperature saved to the health record.":"तापमान स्वास्थ्य रिकॉर्ड में सहेज दिया गया है।", "Health record saved.":"स्वास्थ्य रिकॉर्ड सहेज दिया गया है।", "Photo saved to the health record.":"फोटो स्वास्थ्य रिकॉर्ड में सहेज दिया गया है।", "New cattle record created.":"नया पशु रिकॉर्ड बनाया गया है।"
    },
    bn: {
      "Dairy cow":"দুগ্ধবতী গরু", "Tag ID:":"ট্যাগ আইডি:", "Within usual range":"স্বাভাবিক সীমার মধ্যে", "over usual":"স্বাভাবিকের চেয়ে বেশি", "Latest photo · saved locally":"সর্বশেষ ছবি · স্থানীয়ভাবে সংরক্ষিত", "No photo uploaded":"কোনো ছবি আপলোড করা হয়নি", "Contact a veterinarian now":"এখনই পশু চিকিৎসকের সঙ্গে যোগাযোগ করুন", "The recorded temperature is at or above the urgent threshold.":"নথিভুক্ত তাপমাত্রা জরুরি সীমায় বা তার উপরে আছে।", "Monitor closely and seek veterinary advice if it persists.":"নিবিড় পর্যবেক্ষণ করুন এবং অবস্থা থাকলে পশু চিকিৎসকের পরামর্শ নিন।", "Add cattle":"গবাদি পশু যোগ করুন", "Create a new digital health record.":"নতুন ডিজিটাল স্বাস্থ্য রেকর্ড তৈরি করুন।", "Wellness":"সুস্থতা", "What to log":"কী নথিভুক্ত করবেন", "LIVE":"লাইভ", "PAUSED":"বন্ধ", "Toggle sensor":"সেন্সর পরিবর্তন করুন", "Only record medication prescribed or approved by a qualified veterinarian.":"শুধু যোগ্য পশু চিকিৎসকের প্রেসক্রাইব বা অনুমোদিত ওষুধ নথিভুক্ত করুন।", "24 HOUR":"২৪ ঘণ্টা", "Cancel":"বাতিল", "Save":"সংরক্ষণ করুন", "Add health record":"স্বাস্থ্য রেকর্ড যোগ করুন", "Save an observation, symptom or treatment note to this animal’s history.":"এই প্রাণীর ইতিহাসে পর্যবেক্ষণ, লক্ষণ বা চিকিৎসার নোট সংরক্ষণ করুন।", "Entry type":"এন্ট্রির ধরন", "General observation":"সাধারণ পর্যবেক্ষণ", "Appetite and activity":"ক্ষুধা ও কার্যকলাপ", "Veterinary visit":"পশু চিকিৎসকের পরিদর্শন", "Medication update":"ওষুধ হালনাগাদ", "Details":"বিস্তারিত", "Temperature (optional, °C)":"তাপমাত্রা (ঐচ্ছিক, °C)", "Add photo health check":"ছবির স্বাস্থ্য পরীক্ষা যোগ করুন", "Choose a clear photo. It is saved only in this browser for this prototype.":"একটি স্পষ্ট ছবি বেছে নিন। এই প্রোটোটাইপে এটি শুধু এই ব্রাউজারেই সংরক্ষিত থাকে।", "Photo":"ছবি", "Optional note":"ঐচ্ছিক নোট", "Add diet item":"খাদ্য আইটেম যোগ করুন", "Item name":"আইটেমের নাম", "Amount":"পরিমাণ", "Description":"বিবরণ", "Add medication reminder":"ওষুধের অনুস্মারক যোগ করুন", "Keep dosage and scheduling details in the health record.":"স্বাস্থ্য রেকর্ডে ডোজ ও সময়সূচির বিবরণ রাখুন।", "Medicine name":"ওষুধের নাম", "Dosage / instruction":"ডোজ / নির্দেশ", "Due date or timing":"নির্ধারিত তারিখ বা সময়", "Add local veterinarian":"স্থানীয় পশু চিকিৎসক যোগ করুন", "Save a verified local contact for this prototype.":"এই প্রোটোটাইপের জন্য একটি যাচাইকৃত স্থানীয় যোগাযোগ সংরক্ষণ করুন।", "Veterinarian name":"পশু চিকিৎসকের নাম", "Clinic":"ক্লিনিক", "Distance (optional)":"দূরত্ব (ঐচ্ছিক)", "Hours not recorded":"সময় নথিভুক্ত নয়", "Temperature saved to the health record.":"তাপমাত্রা স্বাস্থ্য রেকর্ডে সংরক্ষিত হয়েছে।", "Health record saved.":"স্বাস্থ্য রেকর্ড সংরক্ষিত হয়েছে।", "Photo saved to the health record.":"ছবি স্বাস্থ্য রেকর্ডে সংরক্ষিত হয়েছে।", "New cattle record created.":"নতুন গবাদি পশুর রেকর্ড তৈরি হয়েছে।"
    },
    mr: {
      "Dairy cow":"दुधाळ गाय", "Tag ID:":"टॅग आयडी:", "Within usual range":"नेहमीच्या मर्यादेत", "over usual":"नेहमीपेक्षा जास्त", "Latest photo · saved locally":"नवीनतम फोटो · स्थानिकरित्या जतन", "No photo uploaded":"फोटो अपलोड केलेला नाही", "Contact a veterinarian now":"आत्ताच पशुवैद्याशी संपर्क करा", "The recorded temperature is at or above the urgent threshold.":"नोंदवलेले तापमान तातडीच्या मर्यादेवर किंवा त्याहून जास्त आहे।", "Monitor closely and seek veterinary advice if it persists.":"काळजीपूर्वक निरीक्षण करा आणि स्थिती कायम राहिल्यास पशुवैद्याचा सल्ला घ्या।", "Add cattle":"जनावर जोडा", "Create a new digital health record.":"नवीन डिजिटल आरोग्य नोंद तयार करा।", "Wellness":"आरोग्य", "What to log":"काय नोंदवायचे", "LIVE":"लाइव्ह", "PAUSED":"थांबवले", "Toggle sensor":"सेन्सर बदला", "Only record medication prescribed or approved by a qualified veterinarian.":"फक्त पात्र पशुवैद्याने लिहिलेली किंवा मंजूर केलेली औषधे नोंदवा।", "24 HOUR":"24 तास", "Cancel":"रद्द करा", "Save":"जतन करा", "Add health record":"आरोग्य नोंद जोडा", "Save an observation, symptom or treatment note to this animal’s history.":"या जनावराच्या इतिहासात निरीक्षण, लक्षण किंवा उपचाराची नोंद जतन करा।", "Entry type":"नोंदीचा प्रकार", "General observation":"सामान्य निरीक्षण", "Appetite and activity":"भूक आणि हालचाल", "Veterinary visit":"पशुवैद्य भेट", "Medication update":"औषध अद्यतन", "Details":"तपशील", "Temperature (optional, °C)":"तापमान (ऐच्छिक, °C)", "Add photo health check":"फोटो आरोग्य तपासणी जोडा", "Choose a clear photo. It is saved only in this browser for this prototype.":"स्पष्ट फोटो निवडा। या प्रोटोटाइपसाठी तो फक्त या ब्राउझरमध्ये जतन होतो।", "Photo":"फोटो", "Optional note":"ऐच्छिक नोंद", "Add diet item":"आहार घटक जोडा", "Item name":"घटकाचे नाव", "Amount":"प्रमाण", "Description":"वर्णन", "Add medication reminder":"औषध स्मरणपत्र जोडा", "Keep dosage and scheduling details in the health record.":"आरोग्य नोंदीमध्ये डोस आणि वेळापत्रकाचा तपशील ठेवा।", "Medicine name":"औषधाचे नाव", "Dosage / instruction":"डोस / सूचना", "Due date or timing":"नियत तारीख किंवा वेळ", "Add local veterinarian":"स्थानिक पशुवैद्य जोडा", "Save a verified local contact for this prototype.":"या प्रोटोटाइपसाठी पडताळलेला स्थानिक संपर्क जतन करा।", "Veterinarian name":"पशुवैद्याचे नाव", "Clinic":"क्लिनिक", "Distance (optional)":"अंतर (ऐच्छिक)", "Hours not recorded":"वेळ नोंदवलेली नाही", "Temperature saved to the health record.":"तापमान आरोग्य नोंदीत जतन केले आहे।", "Health record saved.":"आरोग्य नोंद जतन केली आहे।", "Photo saved to the health record.":"फोटो आरोग्य नोंदीत जतन केला आहे।", "New cattle record created.":"नवीन जनावराची नोंद तयार केली आहे।"
    }
  };
  Object.entries(supplementalWords).forEach(([language, copy]) => Object.assign(words[language], copy));

  const formatDynamicText = (body, language) => {
    const patterns = {
      hi: [
        [/^Here’s (.+)’s current health picture\.$/, "यहाँ $1 के वर्तमान स्वास्थ्य की जानकारी है।"],
        [/^Every entry for (.+) is saved on this device\.$/, "$1 की हर प्रविष्टि इस डिवाइस में सहेजी गई है।"],
        [/^Manage (.+)’s temperature monitoring and add an immediate reading\.$/, "$1 की तापमान निगरानी प्रबंधित करें और तुरंत रीडिंग जोड़ें।"],
        [/^Manage (.+)’s daily feed plan and treatment reminders\.$/, "$1 की दैनिक आहार योजना और उपचार रिमाइंडर प्रबंधित करें।"],
        [/^(.+)’s health history$/, "$1 का स्वास्थ्य इतिहास"],
        [/^(.+)’s usual baseline: (.+)$/, "$1 का सामान्य आधार स्तर: $2"]
      ],
      bn: [
        [/^Here’s (.+)’s current health picture\.$/, "এখানে $1-এর বর্তমান স্বাস্থ্যের চিত্র রয়েছে।"],
        [/^Every entry for (.+) is saved on this device\.$/, "$1-এর প্রতিটি এন্ট্রি এই ডিভাইসে সংরক্ষিত আছে।"],
        [/^Manage (.+)’s temperature monitoring and add an immediate reading\.$/, "$1-এর তাপমাত্রা পর্যবেক্ষণ পরিচালনা করুন এবং তাৎক্ষণিক রিডিং যোগ করুন।"],
        [/^Manage (.+)’s daily feed plan and treatment reminders\.$/, "$1-এর দৈনিক খাদ্য পরিকল্পনা ও চিকিৎসার অনুস্মারক পরিচালনা করুন।"],
        [/^(.+)’s health history$/, "$1-এর স্বাস্থ্য ইতিহাস"],
        [/^(.+)’s usual baseline: (.+)$/, "$1-এর স্বাভাবিক ভিত্তিমাত্রা: $2"]
      ],
      mr: [
        [/^Here’s (.+)’s current health picture\.$/, "येथे $1 च्या सध्याच्या आरोग्याची माहिती आहे।"],
        [/^Every entry for (.+) is saved on this device\.$/, "$1 ची प्रत्येक नोंद या उपकरणावर जतन केली आहे।"],
        [/^Manage (.+)’s temperature monitoring and add an immediate reading\.$/, "$1 चे तापमान निरीक्षण व्यवस्थापित करा आणि त्वरित रीडिंग जोडा।"],
        [/^Manage (.+)’s daily feed plan and treatment reminders\.$/, "$1 ची दैनंदिन आहार योजना आणि उपचार स्मरणपत्रे व्यवस्थापित करा।"],
        [/^(.+)’s health history$/, "$1 चा आरोग्य इतिहास"],
        [/^(.+)’s usual baseline: (.+)$/, "$1 ची नेहमीची आधाररेषा: $2"]
      ]
    };
    for (const [pattern, replacement] of patterns[language] || []) {
      if (pattern.test(body)) return body.replace(pattern, replacement);
    }
    return body;
  };
  const dynamicKeys = ["Tag ID:","Farm boundary radius:","Updated ","Route arrow shows", "GPS alert:","GPS update:"];
  const getLanguage = () => localStorage.getItem("herdcare-language-v1") || "en";
  const translate = (source, language) => {
    if (language === "en" || !source) return source;
    const map = words[language] || {};
    const leading = source.match(/^\s*/)?.[0] || "";
    const trailing = source.match(/\s*$/)?.[0] || "";
    const body = source.trim();
    if (!body) return source;
    let output = map[body] || formatDynamicText(body, language);
    if (output === body) {
      for (const key of dynamicKeys) {
        if (body.startsWith(key) && map[key]) { output = map[key] + body.slice(key.length); break; }
      }
    }
    return leading + output + trailing;
  };
  const apply = () => {
    const language = getLanguage();
    document.documentElement.lang = language;
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(node => {
      if (!node.parentElement || ["SCRIPT","STYLE"].includes(node.parentElement.tagName)) return;
      const original = node.__herdcareOriginal ?? node.__herdcareI18nSource ?? node.nodeValue;
      node.__herdcareI18nSource = original;
      const next = translate(original, language);
      if (node.nodeValue !== next) node.nodeValue = next;
    });
    document.querySelectorAll("[placeholder],[title],[aria-label]").forEach(element => {
      element.__herdcareI18nAttributes ||= {};
      ["placeholder","title","aria-label"].forEach(attribute => {
        if (!element.hasAttribute(attribute)) return;
        const original = element.__herdcareI18nAttributes[attribute] ?? element.getAttribute(attribute);
        element.__herdcareI18nAttributes[attribute] = original;
        const next = translate(original, language);
        if (element.getAttribute(attribute) !== next) element.setAttribute(attribute, next);
      });
    });
    document.querySelectorAll("[data-language-select],#language").forEach(select => { if (select.value !== language) select.value = language; });
  };
  let scheduled = false;
  const schedule = () => {
    if (scheduled) return;
    scheduled = true;
    queueMicrotask(() => { scheduled = false; apply(); });
  };
  document.addEventListener("change", event => {
    if (event.target.matches("[data-language-select],#language")) schedule();
  });
  new MutationObserver(schedule).observe(document.body, {childList:true, subtree:true});
  apply();
})();
